Repository EspressoSystems/espresso-network, pull requests merged in 2024-10, with the labels that each got.

#2137 Check timestamp first when validating header
  types/src/v0/impls/state.rs
Labels: backport main

#2167 Poll L1 more rapidly when we expect a block to be ready soon
  types/src/v0/impls/l1.rs
Labels: backport release-gambit

#2173 fix: use correct PlonkVerifier in deployer.rs
  hotshot-state-prover/Cargo.toml
  utils/src/deployer.rs
Labels: backport release-gambit

#2172 Add option to wait for L1 genesis by timestamp instead of block number
  builder/src/permissioned.rs
  sequencer/src/genesis.rs
  sequencer/src/lib.rs
  types/src/v0/impls/l1.rs
Labels: backport release-gambit

#2148 fix: lower priority fee
  Cargo.lock
  hotshot-state-prover/src/service.rs
  marketplace-builder/Cargo.toml
  utils/Cargo.toml
  utils/src/blocknative.rs
  utils/src/lib.rs
Labels: backport release-gambit

#2197 Update query service
  Cargo.lock
  Cargo.toml
Labels: backport release-rogue

#2208 Add index on `quorum_proposals.leaf_hash`
  sequencer/api/migrations/V42__index_quorum_proposal_leaf_hash.sql
Labels: backport release-rogue

#2215 Do not load entire leaf just to get anchor view
  sequencer/src/context.rs
  sequencer/src/persistence.rs
  sequencer/src/persistence/sql.rs
  types/src/v0/traits.rs
Labels: backport release-rogue

#2244 Bump builder
  Cargo.lock
  Cargo.toml
Labels: backport release-rogue
