Repository EspressoSystems/espresso-network, pull requests merged in 2025-04, with the labels that each got.

#2982 fix: G2PointSol to BLSPubKey conversion
  contracts/rust/adapter/src/stake_table.rs
Labels: backport release-combined-water

#3006 Refactor state prover logic
  hotshot-state-prover/src/circuit.rs
  hotshot-state-prover/src/mock_ledger.rs
  hotshot-state-prover/src/service.rs
  hotshot-types/src/light_client.rs
  hotshot-types/src/signature_key.rs
  hotshot-types/src/vote.rs
  sequencer/src/state_signature.rs
  sequencer/src/state_signature/relay_server.rs
Labels: backport release-combined-water

#3012 reward balance endpoint
  sequencer/api/fee.toml
  sequencer/api/reward.toml
  sequencer/src/api/endpoints.rs
  sequencer/src/api/options.rs
  types/src/v0/impls/reward.rs
Labels: backport release-combined-water

#3054 remove offset from types migration
  hotshot-query-service/src/data_source/storage/sql.rs
  sequencer/src/persistence/sql.rs
  types/src/v0/impls/stake_table.rs
Labels: backport main

#3057 Remove ORDER BY from types migration query
  hotshot-query-service/src/data_source/storage/sql.rs
  sequencer/src/persistence/sql.rs
Labels: backport main

#3103 use correct to_block for stake table events fetching
  types/src/v0/impls/stake_table.rs
Labels: backport release-fix-upgrade

#3108 Fix Synced Block Height Metric in new Version
  crates/hotshot/task-impls/src/helpers.rs
Labels: backport release-fix-upgrade

#3153 don't allow super high requests to stake table endpoint
  sequencer/src/api.rs
Labels: backport release-fix-upgrade

#3130 Remove failed stake table catchup request to allow new catchup request
  crates/hotshot/types/src/epoch_membership.rs
Labels: backport release-fix-upgrade
